services:
  postgres:
    image: postgres:16
    container_name: match-immo-postgres
    environment:
      POSTGRES_DB: match_immo
      POSTGRES_USER: match_immo
      POSTGRES_PASSWORD: match_immo
    ports:
      - "5433:5432"
    volumes:
      - match-immo-postgres-data:/var/lib/postgresql/data

volumes:
  match-immo-postgres-data:
