apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: matchimmo-pg

spec:
  instances: 2

  imageName: ghcr.io/cloudnative-pg/postgresql:16.15-202608310817-system-trixie

  storage:
    size: 10Gi
