-- ============================================================
-- Projet RNCP40573 - Chasse immobiliere
-- Phase 2 - Modele cible
-- Fichier : migration.sql
-- SGBD    : PostgreSQL
--
-- Objectif :
-- Creer le schema transactionnel cible a partir du MLD final valide.
--
-- Important :
-- La reprise des donnees de l'ancien schema est traitee separement
-- dans reprise-donnees.sql.
-- ============================================================

BEGIN;

-- ============================================================
-- 1. SCHEMA CIBLE
-- ============================================================

DROP SCHEMA IF EXISTS fil_rouge_cible CASCADE;

CREATE SCHEMA fil_rouge_cible;

SET search_path TO fil_rouge_cible;


-- ============================================================
-- 2. UTILISATEUR
-- ============================================================

CREATE TABLE utilisateur (
    id_utilisateur INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nom VARCHAR(80) NOT NULL,
    prenom VARCHAR(80) NOT NULL,

    email VARCHAR(150) NOT NULL
        UNIQUE,

    telephone VARCHAR(30),
    statut_compte VARCHAR(30) NOT NULL
);


-- ============================================================
-- 3. CLIENT
-- Specialisation de UTILISATEUR : cle primaire partagee
-- ============================================================

CREATE TABLE client (
    id_client INTEGER
        PRIMARY KEY,

    statut VARCHAR(30) NOT NULL,

    CONSTRAINT fk_client_utilisateur
        FOREIGN KEY (id_client)
        REFERENCES utilisateur(id_utilisateur)
);


-- ============================================================
-- 4. CHASSEUR
-- Specialisation de UTILISATEUR : cle primaire partagee
-- ============================================================

CREATE TABLE chasseur (
    id_chasseur INTEGER
        PRIMARY KEY,

    matricule VARCHAR(50) NOT NULL
        UNIQUE,

    disponibilite VARCHAR(50),

    CONSTRAINT fk_chasseur_utilisateur
        FOREIGN KEY (id_chasseur)
        REFERENCES utilisateur(id_utilisateur)
);


-- ============================================================
-- 5. DEMANDE
-- ============================================================

CREATE TABLE demande (
    id_demande INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    client_id INTEGER NOT NULL,
    date_creation DATE NOT NULL,
    statut VARCHAR(30) NOT NULL,

    CONSTRAINT fk_demande_client
        FOREIGN KEY (client_id)
        REFERENCES client(id_client)
);


-- ============================================================
-- 6. AFFECTATION
-- Historise les propositions de prise en charge par les chasseurs
-- ============================================================

CREATE TABLE affectation (
    id_affectation INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    demande_id INTEGER NOT NULL,
    chasseur_id INTEGER NOT NULL,

    date_affectation TIMESTAMP NOT NULL,
    date_reponse TIMESTAMP,
    statut VARCHAR(30) NOT NULL,
    motif_refus TEXT,

    CONSTRAINT fk_affectation_demande
        FOREIGN KEY (demande_id)
        REFERENCES demande(id_demande),

    CONSTRAINT fk_affectation_chasseur
        FOREIGN KEY (chasseur_id)
        REFERENCES chasseur(id_chasseur),

    CONSTRAINT chk_affectation_dates
        CHECK (
            date_reponse IS NULL
            OR date_reponse >= date_affectation
        )
);


-- ============================================================
-- 7. VERSION_DEMANDE
-- ============================================================

CREATE TABLE version_demande (
    id_version INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    demande_id INTEGER NOT NULL,
    auteur_id INTEGER NOT NULL,

    numero_version INTEGER NOT NULL,
    date_version TIMESTAMP NOT NULL,

    budget_min NUMERIC(12,2),
    budget_max NUMERIC(12,2),

    surface_min NUMERIC(10,2),
    surface_max NUMERIC(10,2),

    nb_pieces_min INTEGER,

    motif_modification TEXT,

    est_courante BOOLEAN NOT NULL
        DEFAULT FALSE,

    CONSTRAINT fk_version_demande
        FOREIGN KEY (demande_id)
        REFERENCES demande(id_demande),

    CONSTRAINT fk_version_auteur
        FOREIGN KEY (auteur_id)
        REFERENCES utilisateur(id_utilisateur),

    CONSTRAINT uq_version_demande_numero
        UNIQUE (demande_id, numero_version),

    CONSTRAINT chk_version_numero
        CHECK (numero_version > 0),

    CONSTRAINT chk_version_budgets
        CHECK (
            (budget_min IS NULL OR budget_min >= 0)
            AND (budget_max IS NULL OR budget_max >= 0)
            AND (
                budget_min IS NULL
                OR budget_max IS NULL
                OR budget_min <= budget_max
            )
        ),

    CONSTRAINT chk_version_surfaces
        CHECK (
            (surface_min IS NULL OR surface_min >= 0)
            AND (surface_max IS NULL OR surface_max >= 0)
            AND (
                surface_min IS NULL
                OR surface_max IS NULL
                OR surface_min <= surface_max
            )
        ),

    CONSTRAINT chk_version_nb_pieces
        CHECK (
            nb_pieces_min IS NULL
            OR nb_pieces_min >= 0
        )
);

-- Une seule version courante par demande.
CREATE UNIQUE INDEX uq_version_demande_courante
    ON version_demande (demande_id)
    WHERE est_courante = TRUE;


-- ============================================================
-- 8. SECTEUR
-- ============================================================

CREATE TABLE secteur (
    id_secteur INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    ville VARCHAR(80) NOT NULL,
    quartier VARCHAR(80),
    code_postal VARCHAR(10) NOT NULL
);


-- ============================================================
-- 9. VERSION_DEMANDE_SECTEUR
-- Association N:N entre VERSION_DEMANDE et SECTEUR
-- ============================================================

CREATE TABLE version_demande_secteur (
    version_id INTEGER NOT NULL,
    secteur_id INTEGER NOT NULL,

    CONSTRAINT pk_version_demande_secteur
        PRIMARY KEY (version_id, secteur_id),

    CONSTRAINT fk_vds_version
        FOREIGN KEY (version_id)
        REFERENCES version_demande(id_version),

    CONSTRAINT fk_vds_secteur
        FOREIGN KEY (secteur_id)
        REFERENCES secteur(id_secteur)
);


-- ============================================================
-- 10. MANDAT
-- ============================================================

CREATE TABLE mandat (
    id_mandat INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    demande_id INTEGER NOT NULL,
    client_id INTEGER NOT NULL,
    chasseur_id INTEGER NOT NULL,

    mandat_precedent_id INTEGER
        UNIQUE,

    date_signature DATE NOT NULL,
    mode_signature VARCHAR(30) NOT NULL,

    exclusif BOOLEAN NOT NULL
        DEFAULT FALSE,

    date_fin DATE NOT NULL,
    statut VARCHAR(30) NOT NULL,

    CONSTRAINT fk_mandat_demande
        FOREIGN KEY (demande_id)
        REFERENCES demande(id_demande),

    CONSTRAINT fk_mandat_client
        FOREIGN KEY (client_id)
        REFERENCES client(id_client),

    CONSTRAINT fk_mandat_chasseur
        FOREIGN KEY (chasseur_id)
        REFERENCES chasseur(id_chasseur),

    CONSTRAINT fk_mandat_precedent
        FOREIGN KEY (mandat_precedent_id)
        REFERENCES mandat(id_mandat),

    CONSTRAINT chk_mandat_dates
        CHECK (
            date_fin =
            (date_signature + INTERVAL '6 months')::DATE
        ),

    CONSTRAINT chk_mandat_renouvellement
        CHECK (
            mandat_precedent_id IS NULL
            OR mandat_precedent_id <> id_mandat
        )
);


-- ============================================================
-- 11. BIEN
-- ============================================================

CREATE TABLE bien (
    id_bien INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    secteur_id INTEGER NOT NULL,

    adresse VARCHAR(255) NOT NULL,
    type_bien VARCHAR(50) NOT NULL,

    prix NUMERIC(12,2) NOT NULL,
    surface NUMERIC(10,2),
    nombre_pieces INTEGER,

    dpe VARCHAR(10),
    description TEXT,

    CONSTRAINT fk_bien_secteur
        FOREIGN KEY (secteur_id)
        REFERENCES secteur(id_secteur),

    CONSTRAINT chk_bien_prix
        CHECK (prix >= 0),

    CONSTRAINT chk_bien_surface
        CHECK (
            surface IS NULL
            OR surface >= 0
        ),

    CONSTRAINT chk_bien_nombre_pieces
        CHECK (
            nombre_pieces IS NULL
            OR nombre_pieces >= 0
        )
);


-- ============================================================
-- 12. VENDEUR
-- ============================================================

CREATE TABLE vendeur (
    id_vendeur INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nom VARCHAR(80) NOT NULL,
    prenom VARCHAR(80) NOT NULL,
    email VARCHAR(150),
    telephone VARCHAR(30)
);


-- ============================================================
-- 13. VENDEUR_BIEN
-- Association N:N entre VENDEUR et BIEN
-- ============================================================

CREATE TABLE vendeur_bien (
    vendeur_id INTEGER NOT NULL,
    bien_id INTEGER NOT NULL,

    CONSTRAINT pk_vendeur_bien
        PRIMARY KEY (vendeur_id, bien_id),

    CONSTRAINT fk_vendeur_bien_vendeur
        FOREIGN KEY (vendeur_id)
        REFERENCES vendeur(id_vendeur),

    CONSTRAINT fk_vendeur_bien_bien
        FOREIGN KEY (bien_id)
        REFERENCES bien(id_bien)
);


-- ============================================================
-- 14. PRESENTATION
-- ============================================================

CREATE TABLE presentation (
    id_presentation INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    mandat_id INTEGER NOT NULL,
    bien_id INTEGER NOT NULL,

    date_presentation TIMESTAMP NOT NULL,
    statut VARCHAR(30) NOT NULL,

    priorite_client INTEGER,
    decision_client VARCHAR(50),
    observations TEXT,

    CONSTRAINT fk_presentation_mandat
        FOREIGN KEY (mandat_id)
        REFERENCES mandat(id_mandat),

    CONSTRAINT fk_presentation_bien
        FOREIGN KEY (bien_id)
        REFERENCES bien(id_bien),

    CONSTRAINT chk_presentation_priorite
        CHECK (
            priorite_client IS NULL
            OR priorite_client >= 0
        )
);


-- ============================================================
-- 15. COMMENTAIRE
-- ============================================================

CREATE TABLE commentaire (
    id_commentaire INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    presentation_id INTEGER NOT NULL,
    auteur_id INTEGER NOT NULL,

    texte TEXT NOT NULL,
    date_commentaire TIMESTAMP NOT NULL,

    CONSTRAINT fk_commentaire_presentation
        FOREIGN KEY (presentation_id)
        REFERENCES presentation(id_presentation),

    CONSTRAINT fk_commentaire_auteur
        FOREIGN KEY (auteur_id)
        REFERENCES utilisateur(id_utilisateur)
);


-- ============================================================
-- 16. VISITE
-- ============================================================

CREATE TABLE visite (
    id_visite INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    presentation_id INTEGER NOT NULL,

    date_visite TIMESTAMP NOT NULL,
    retour_client TEXT,
    interet VARCHAR(50),

    CONSTRAINT fk_visite_presentation
        FOREIGN KEY (presentation_id)
        REFERENCES presentation(id_presentation)
);


-- ============================================================
-- 17. AVIS_CHASSEUR
-- ============================================================

CREATE TABLE avis_chasseur (
    id_avis INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    presentation_id INTEGER NOT NULL,
    chasseur_id INTEGER NOT NULL,

    date_avis TIMESTAMP NOT NULL,
    texte TEXT NOT NULL,

    CONSTRAINT fk_avis_presentation
        FOREIGN KEY (presentation_id)
        REFERENCES presentation(id_presentation),

    CONSTRAINT fk_avis_chasseur
        FOREIGN KEY (chasseur_id)
        REFERENCES chasseur(id_chasseur)
);


-- ============================================================
-- 18. MEDIA_AVIS
-- ============================================================

CREATE TABLE media_avis (
    id_media INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    avis_id INTEGER NOT NULL,

    type_media VARCHAR(30) NOT NULL,
    emplacement TEXT NOT NULL,

    CONSTRAINT fk_media_avis
        FOREIGN KEY (avis_id)
        REFERENCES avis_chasseur(id_avis)
);


-- ============================================================
-- 19. OFFRE
-- ============================================================

CREATE TABLE offre (
    id_offre INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    presentation_id INTEGER NOT NULL,

    date_offre DATE NOT NULL,
    montant_offre NUMERIC(12,2) NOT NULL,
    condition_financement TEXT,
    statut VARCHAR(30) NOT NULL,

    CONSTRAINT fk_offre_presentation
        FOREIGN KEY (presentation_id)
        REFERENCES presentation(id_presentation),

    CONSTRAINT chk_offre_montant
        CHECK (montant_offre >= 0)
);


-- ============================================================
-- 20. NOTAIRE
-- ============================================================

CREATE TABLE notaire (
    id_notaire INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nom VARCHAR(80) NOT NULL,
    prenom VARCHAR(80) NOT NULL,
    email VARCHAR(150),
    telephone VARCHAR(30)
);


-- ============================================================
-- 21. ACTE_AUTHENTIQUE
-- Une offre peut donner lieu a au plus un acte
-- ============================================================

CREATE TABLE acte_authentique (
    id_acte INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    offre_id INTEGER NOT NULL
        UNIQUE,

    notaire_id INTEGER NOT NULL,

    date_acte DATE NOT NULL,
    prix_vente NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_acte_offre
        FOREIGN KEY (offre_id)
        REFERENCES offre(id_offre),

    CONSTRAINT fk_acte_notaire
        FOREIGN KEY (notaire_id)
        REFERENCES notaire(id_notaire),

    CONSTRAINT chk_acte_prix
        CHECK (prix_vente >= 0)
);


-- ============================================================
-- 22. HONORAIRES
-- Relation 1:1 avec ACTE_AUTHENTIQUE cote enregistrement
-- ============================================================

CREATE TABLE honoraires (
    id_honoraires INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    acte_id INTEGER NOT NULL
        UNIQUE,

    montant_fixe NUMERIC(12,2),
    pourcentage NUMERIC(7,4),
    montant_total NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_honoraires_acte
        FOREIGN KEY (acte_id)
        REFERENCES acte_authentique(id_acte),

    CONSTRAINT chk_honoraires_montants
        CHECK (
            (montant_fixe IS NULL OR montant_fixe >= 0)
            AND montant_total >= 0
        ),

    CONSTRAINT chk_honoraires_pourcentage
        CHECK (
            pourcentage IS NULL
            OR pourcentage >= 0
        )
);


-- ============================================================
-- 23. BAREME_COMMISSION
-- ============================================================

CREATE TABLE bareme_commission (
    id_bareme INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    chasseur_id INTEGER NOT NULL,

    date_debut_validite DATE NOT NULL,
    date_fin_validite DATE,

    CONSTRAINT fk_bareme_chasseur
        FOREIGN KEY (chasseur_id)
        REFERENCES chasseur(id_chasseur),

    CONSTRAINT chk_bareme_dates
        CHECK (
            date_fin_validite IS NULL
            OR date_fin_validite >= date_debut_validite
        )
);


-- ============================================================
-- 24. TRANCHE_COMMISSION
-- ============================================================

CREATE TABLE tranche_commission (
    id_tranche INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    bareme_id INTEGER NOT NULL,

    montant_min NUMERIC(12,2) NOT NULL,
    montant_max NUMERIC(12,2) NOT NULL,
    taux_pourcentage NUMERIC(7,4) NOT NULL,

    CONSTRAINT fk_tranche_bareme
        FOREIGN KEY (bareme_id)
        REFERENCES bareme_commission(id_bareme),

    CONSTRAINT chk_tranche_montants
        CHECK (
            montant_min >= 0
            AND montant_max >= 0
            AND montant_min <= montant_max
        ),

    CONSTRAINT chk_tranche_taux
        CHECK (taux_pourcentage >= 0)
);


-- ============================================================
-- 25. COMMISSION
-- ============================================================

CREATE TABLE commission (
    id_commission INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    honoraires_id INTEGER NOT NULL
        UNIQUE,

    chasseur_id INTEGER NOT NULL,
    tranche_id INTEGER NOT NULL,

    montant_commission NUMERIC(12,2) NOT NULL,
    taux_applique NUMERIC(7,4) NOT NULL,

    CONSTRAINT fk_commission_honoraires
        FOREIGN KEY (honoraires_id)
        REFERENCES honoraires(id_honoraires),

    CONSTRAINT fk_commission_chasseur
        FOREIGN KEY (chasseur_id)
        REFERENCES chasseur(id_chasseur),

    CONSTRAINT fk_commission_tranche
        FOREIGN KEY (tranche_id)
        REFERENCES tranche_commission(id_tranche),

    CONSTRAINT chk_commission_montant
        CHECK (montant_commission >= 0),

    CONSTRAINT chk_commission_taux
        CHECK (taux_applique >= 0)
);


-- ============================================================
-- 26. FACTURE_CHASSEUR
-- ============================================================

CREATE TABLE facture_chasseur (
    id_facture INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    commission_id INTEGER NOT NULL
        UNIQUE,

    chasseur_id INTEGER NOT NULL,

    reference VARCHAR(100) NOT NULL
        UNIQUE,

    date_depot DATE NOT NULL,
    montant NUMERIC(12,2) NOT NULL,
    statut VARCHAR(30) NOT NULL,
    date_verification DATE,

    CONSTRAINT fk_facture_commission
        FOREIGN KEY (commission_id)
        REFERENCES commission(id_commission),

    CONSTRAINT fk_facture_chasseur
        FOREIGN KEY (chasseur_id)
        REFERENCES chasseur(id_chasseur),

    CONSTRAINT chk_facture_montant
        CHECK (montant >= 0),

    CONSTRAINT chk_facture_dates
        CHECK (
            date_verification IS NULL
            OR date_verification >= date_depot
        )
);


-- ============================================================
-- 27. PAIEMENT
-- ============================================================

CREATE TABLE paiement (
    id_paiement INTEGER GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    facture_id INTEGER NOT NULL,

    montant_paye NUMERIC(12,2) NOT NULL,
    date_paiement DATE NOT NULL,
    statut VARCHAR(30) NOT NULL,

    CONSTRAINT fk_paiement_facture
        FOREIGN KEY (facture_id)
        REFERENCES facture_chasseur(id_facture),

    CONSTRAINT chk_paiement_montant
        CHECK (montant_paye >= 0)
);


-- ============================================================
-- 28. INDEX UTILES AUX CLES ETRANGERES
-- ============================================================
-- PostgreSQL ne cree pas automatiquement d'index sur les colonnes FK.
-- Ces index facilitent les jointures et les recherches courantes.

CREATE INDEX idx_demande_client
    ON demande (client_id);

CREATE INDEX idx_affectation_demande
    ON affectation (demande_id);

CREATE INDEX idx_affectation_chasseur
    ON affectation (chasseur_id);

CREATE INDEX idx_version_demande
    ON version_demande (demande_id);

CREATE INDEX idx_version_auteur
    ON version_demande (auteur_id);

CREATE INDEX idx_mandat_demande
    ON mandat (demande_id);

CREATE INDEX idx_mandat_client
    ON mandat (client_id);

CREATE INDEX idx_mandat_chasseur
    ON mandat (chasseur_id);

CREATE INDEX idx_bien_secteur
    ON bien (secteur_id);

CREATE INDEX idx_presentation_mandat
    ON presentation (mandat_id);

CREATE INDEX idx_presentation_bien
    ON presentation (bien_id);

CREATE INDEX idx_commentaire_presentation
    ON commentaire (presentation_id);

CREATE INDEX idx_commentaire_auteur
    ON commentaire (auteur_id);

CREATE INDEX idx_visite_presentation
    ON visite (presentation_id);

CREATE INDEX idx_avis_presentation
    ON avis_chasseur (presentation_id);

CREATE INDEX idx_avis_chasseur
    ON avis_chasseur (chasseur_id);

CREATE INDEX idx_media_avis
    ON media_avis (avis_id);

CREATE INDEX idx_offre_presentation
    ON offre (presentation_id);

CREATE INDEX idx_acte_notaire
    ON acte_authentique (notaire_id);

CREATE INDEX idx_bareme_chasseur
    ON bareme_commission (chasseur_id);

CREATE INDEX idx_tranche_bareme
    ON tranche_commission (bareme_id);

CREATE INDEX idx_commission_chasseur
    ON commission (chasseur_id);

CREATE INDEX idx_commission_tranche
    ON commission (tranche_id);

CREATE INDEX idx_facture_chasseur
    ON facture_chasseur (chasseur_id);

CREATE INDEX idx_paiement_facture
    ON paiement (facture_id);


-- ============================================================
-- 29. REGLES NON ENFORCEES PAR UNE SIMPLE CONTRAINTE DE TABLE
-- ============================================================
--
-- Certaines regles du MCD / des regles de gestion necessitent
-- un controle transactionnel, un trigger ou la couche applicative :
--
-- - une DEMANDE doit toujours posseder au moins une VERSION_DEMANDE ;
-- - une VERSION_DEMANDE doit cibler au moins un SECTEUR ;
-- - un BAREME_COMMISSION doit contenir au moins une TRANCHE_COMMISSION ;
-- - un mandat exclusif actif doit bloquer les autres mandats actifs
--   incompatibles pour la meme demande ;
-- - les periodes de baremes d'un meme chasseur ne doivent pas rendre
--   le bareme applicable ambigu ;
-- - les tranches d'un meme bareme ne doivent pas se chevaucher ;
-- - le CLIENT et le CHASSEUR d'un mandat doivent rester coherents avec
--   la demande et son affectation ;
-- - le CHASSEUR d'une commission, sa tranche, son bareme et sa facture
--   doivent rester coherents entre eux ;
-- - la somme des paiements effectues d'une facture ne doit pas depasser
--   le montant a regler ;
-- - certaines chronologies inter-tables (presentation, visite, offre,
--   acte, facture, paiement) necessitent un controle transverse.
--
-- Ces regles seront couvertes par les controles applicatifs,
-- les triggers si necessaires et le plan de tests.
-- ============================================================

COMMIT;
